use_gpu: True
device: 0
early_stop:
  patience: 5
seed: 12345
federate:
  mode: standalone
  total_round_num: 1000
  sample_client_rate: 0.1
  client_num: 200
data:
  root: data/
  type: femnist
  splits: [0.6,0.2,0.2]
  subsample: 0.05
  transform: [['ToTensor'], ['Normalize', {'mean': [0.9637], 'std': [0.1592]}]]
dataloader:
  batch_size: 10
  num_workers: 0
model:
  type: convnet2
  hidden: 2048
  out_channels: 62
train:
  local_update_steps: 2
  batch_or_epoch: epoch
  optimizer:
    lr: 0.1
    weight_decay: 0.0
grad:
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 1
  split: ['test', 'val']
  metrics: ['acc', 'correct', 'poison_attack_acc']
attack:
  setting: 'fix'
  freq: 10
  attack_method: 'backdoor'
  attacker_id: 1
  label_type: 'dirty'
  trigger_type: gridTrigger
  target_label_ind: 1
  self_opt: False
  self_lr: 0.1
  self_epoch: 6
  scale_poisoning: False
  scale_para: 5.0
  mean: [0.9637]
  std: [0.1592]
